"""
Easy #2 — Arrays & Hashing

Problem: Most Frequent Error Code

You are given a list of integers errors, where each integer represents an error code generated by a system.

Return the error code that appears most frequently.

If multiple error codes have the same highest frequency, return the one that appeared first in the original list.
"""

def most_frequent_error(errors):
    error_rate = {}
    for error in errors:
        if error not in error_rate: #error_rate[error] = error_rate.get(error, 0) + 1 this also works for the if else statement
            error_rate[error] = 1

        else: error_rate[error] += 1

    return (max(error_rate, key=error_rate.get))


print(most_frequent_error([404, 500, 404, 403, 500, 404]))
# Expected: 404

print(most_frequent_error([7, 3, 7, 3]))
# Expected: 7

print(most_frequent_error([10]))
# Expected: 10

print(most_frequent_error([1, 2, 3, 2, 3, 3]))
# Expected: 3